# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/etorres/CarApp/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 202)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.reverse_button = QtWidgets.QPushButton(self.groupBox)
        self.reverse_button.setEnabled(False)
        self.reverse_button.setObjectName("reverse_button")
        self.gridLayout.addWidget(self.reverse_button, 1, 1, 1, 1)
        self.decelerate_button = QtWidgets.QPushButton(self.groupBox)
        self.decelerate_button.setEnabled(False)
        self.decelerate_button.setObjectName("decelerate_button")
        self.gridLayout.addWidget(self.decelerate_button, 1, 4, 1, 1)
        self.right_button = QtWidgets.QPushButton(self.groupBox)
        self.right_button.setEnabled(False)
        self.right_button.setObjectName("right_button")
        self.gridLayout.addWidget(self.right_button, 1, 2, 1, 1)
        self.forward_button = QtWidgets.QPushButton(self.groupBox)
        self.forward_button.setEnabled(False)
        self.forward_button.setObjectName("forward_button")
        self.gridLayout.addWidget(self.forward_button, 0, 1, 1, 1)
        self.left_button = QtWidgets.QPushButton(self.groupBox)
        self.left_button.setEnabled(False)
        self.left_button.setObjectName("left_button")
        self.gridLayout.addWidget(self.left_button, 1, 0, 1, 1)
        self.accelerate_button = QtWidgets.QPushButton(self.groupBox)
        self.accelerate_button.setEnabled(False)
        self.accelerate_button.setObjectName("accelerate_button")
        self.gridLayout.addWidget(self.accelerate_button, 0, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 3, 2, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connect_button = QtWidgets.QPushButton(self.groupBox_2)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout.addWidget(self.connect_button)
        self.disconnect_button = QtWidgets.QPushButton(self.groupBox_2)
        self.disconnect_button.setEnabled(False)
        self.disconnect_button.setObjectName("disconnect_button")
        self.verticalLayout.addWidget(self.disconnect_button)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 490, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.forward_button.pressed.connect(MainWindow.forward_button_pressed)
        self.forward_button.released.connect(MainWindow.button_released)
        self.reverse_button.pressed.connect(MainWindow.reverse_button_pressed)
        self.reverse_button.released.connect(MainWindow.button_released)
        self.left_button.pressed.connect(MainWindow.left_button_pressed)
        self.left_button.released.connect(MainWindow.button_released)
        self.right_button.pressed.connect(MainWindow.right_button_pressed)
        self.right_button.released.connect(MainWindow.button_released)
        self.connect_button.clicked.connect(MainWindow.connect_button_clicked)
        self.disconnect_button.clicked.connect(MainWindow.disconnect_button_clicked)
        self.accelerate_button.pressed.connect(MainWindow.accelerate_button_pressed)
        self.decelerate_button.pressed.connect(MainWindow.decelerate_button_pressed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Controls"))
        self.reverse_button.setText(_translate("MainWindow", " v"))
        self.decelerate_button.setText(_translate("MainWindow", "Decelerate"))
        self.right_button.setText(_translate("MainWindow", ">"))
        self.forward_button.setText(_translate("MainWindow", "^"))
        self.left_button.setText(_translate("MainWindow", "<"))
        self.accelerate_button.setText(_translate("MainWindow", "Accelerate"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Connection"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.disconnect_button.setText(_translate("MainWindow", "Disconnect"))

