from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMainWindow
from autogenerated import Ui_MainWindow


import socket
import sys


class CarApp(QMainWindow):

    def __init__(self):
        QMainWindow.__init__(self)
        self._obj = Ui_MainWindow()
        self._obj.setupUi(self)
        self._socket = None
        self._key_bindings = {
            "W": self.forward_button_pressed,
            "S": self.reverse_button_pressed,
            "A": self.left_button_pressed,
            "D": self.right_button_pressed,
            "O": self.accelerate_button_pressed,
            "L": self.decelerate_button_pressed
        }

    def _enable_controls(self):
        self._obj.disconnect_button.setEnabled(True)
        self._obj.connect_button.setEnabled(False)
        self._obj.forward_button.setEnabled(True)
        self._obj.reverse_button.setEnabled(True)
        self._obj.left_button.setEnabled(True)
        self._obj.right_button.setEnabled(True)
        self._obj.accelerate_button.setEnabled(True)
        self._obj.decelerate_button.setEnabled(True)

    def _disable_controls(self):
        self._obj.disconnect_button.setEnabled(False)
        self._obj.connect_button.setEnabled(True)
        self._obj.forward_button.setEnabled(False)
        self._obj.reverse_button.setEnabled(False)
        self._obj.left_button.setEnabled(False)
        self._obj.right_button.setEnabled(False)
        self._obj.accelerate_button.setEnabled(False)
        self._obj.decelerate_button.setEnabled(False)

    def connect_button_clicked(self):
        self._socket = socket.socket()
        self._socket.connect(('192.168.4.1', 54321))
        self._enable_controls()

    def disconnect_button_clicked(self):
        self._socket.close()
        self._disable_controls()

    def forward_button_pressed(self):
        self._socket.send(b'FORWARD')

    def reverse_button_pressed(self):
        self._socket.send(b'REVERSE')

    def left_button_pressed(self):
        self._socket.send(b'TURN_RIGHT')

    def right_button_pressed(self):
        self._socket.send(b'TURN_LEFT')

    def accelerate_button_pressed(self):
        self._socket.send(b'ACCELERATE')

    def decelerate_button_pressed(self):
        self._socket.send(b'DECELERATE')

    def button_released(self):
        self._socket.send(b'STOP')

    def keyPressEvent(self, e):
        key_pressed = chr(e.key())
        if key_pressed in self._key_bindings:
            self._key_bindings[key_pressed]()

    def keyReleaseEvent(self, e):
        key_pressed = chr(e.key())
        if (key_pressed == "W" or key_pressed == "S" or
                key_pressed == "A" or key_pressed == "D"):
            self.button_released()


def main():
    app = QApplication(sys.argv)
    main_window = CarApp()

    # Init PyQt mainloop
    main_window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
